[package]
name = "vbf-tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "2", features = ["suggestions", "color", "wrap_help"]}
crc = "2.1.0"
json = "0.12.4"
sha2 = "0.10.2"
